apiVersion: v1
kind: ServiceAccount
metadata:
  name: amp-system
  namespace: amp-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: amp-system
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: amp-system
  namespace: amp-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: amp-system
subjects:
  - kind: ServiceAccount
    name: amp-system
    namespace: amp-system