apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: amp
  labels:
    app: amp
webhooks:
  - name: amp.txn2.com
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
    timeoutSeconds: 10
    clientConfig:
      service:
        name: amp
        namespace: amp-system
        path: "/mutate"
      caBundle: REPLACE
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        scope: "Namespaced"
    namespaceSelector:
      matchLabels:
        amp.txn2.com/enabled: "true"